Create french translation fr.json
rospogrigio/localtuya pull request #1439
Opened 2023-06-17 15:23 UTC by alray31

Added french translation

2023-07-06 01:28 UTC, voxlinou1 requested changes
Petit problème au niveau de la ligne 27 avec les `"` sans anti-slash.

2023-07-06 13:23 UTC, alray31 commented
> Petit problème au niveau de la ligne 27 avec les `"` sans anti-slash.

Je crois qu'on parlais plutôt de la ligne 37? C'est corrigé avec des single ' plutôt que des double " pour garder la forme original dans en.json qui utilise des single '

Merci

2023-09-22 12:06 UTC, CloCkWeRX commented
I don't speak french, but the parse issues seem to have been sorted and google translate turns it back into something intelligible..

2023-09-22 12:06 UTC, CloCkWeRX approved these changes

2023-10-02 08:40 UTC, CloCkWeRX commented
@rospogrigio I think this one might be a good candidate for merging. @makouille any further suggests as a  french speaker?

2023-11-01 12:19 UTC, makouille commented
> @rospogrigio I think this one might be a good candidate for merging. @makouille any further suggests as a french speaker?

Nope, all done

2023-11-01 12:19 UTC, makouille approved these changes

2024-05-09 01:57 UTC, closed without merging