Support adding and removing entities to devices
rospogrigio/localtuya pull request #191
Opened 2020-11-25 20:22 UTC by postlund

This is not what I should be working on, but I had most of the code sitting on a branch so I decided to finish it.

New  entities can be added via + button under Integrations (like when adding a new device, but select an existing device instead) and entities can be removed from Options.

2020-11-26 10:01 UTC, ultratoto14 commented
Hi @postlund, just tested it, here are my remarks:

- When adding a new entity to an existing one, the already used DP ids are proposed.
- At the end the label is not what is expected, "Abandonné" means "canceled"
![Canceled](https://user-images.githubusercontent.com/3328573/100335097-e070e780-2fd4-11eb-880f-91ae92ff8654.png)
- At the same time i have an exception in the logs, but the entity was well created:
```
2020-11-26 10:53:01 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry Tempo for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 321, in async_unload
    result = await component.async_unload_entry(hass, self)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 72, in async_unload_entry
    return await hass.data[DOMAIN].async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 172, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
```
- When trying to add a new entity, yaml defined entries are proposed, if i choose one i have an error, nothing in the logs
![Error](https://user-images.githubusercontent.com/3328573/100335346-2c239100-2fd5-11eb-80fa-114d84a8f949.PNG)

2020-11-26 11:12 UTC, postlund commented
Thanks for testing @ultratoto14! Let's see if I can answer...

Hmm, that's strange. Is it always like that or only when you add a new entity to a device that you added during the same "session"? Because I know that the browser sometimes cache values and fill those in for some reason. I at least don't have any code for auto-filling values (that's part of #125, which isn't merged yet).

That's a limitation of the entry flow framework. There's only two ways out: creating a new config entry or aborting (yielding the "canceled" message). Since we already have a config entry, that leaves out the first one (which also would request the user to assign the device to a room again), leaving only the abort method. Fact is that this is the de-facto way of doing things like this, e.g. when reconfiguring credentials for a device. So you will see it in the built in components as well.

The exception I don't know the reason for, will have to look into that.

Right, good catch. I will make sure to filter out devices set up via YAML.

2020-12-17 07:43 UTC, ultratoto14 commented
@postlund should I retest this one ?

2020-12-17 08:27 UTC, postlund commented
@ultratoto14 Yes please, forgot to ping you about it.

2020-12-17 09:59 UTC, ultratoto14 approved these changes
Code looks good 👍 
Tests are Ok:

- Adding new device 👍  
- Adding entity to device 👍 
- Removing entity from device 👍 
- YAML devices not listed 👍 
- Already configured and not yet configured are there in list 👍

2020-12-17 10:53 UTC, postlund commented
Great! 👍 Let's merge before I charge my mind.

2020-12-17 13:19 UTC, ultratoto14 requested changes

2020-12-17 13:19 UTC, ultratoto14 commented on custom_components/localtuya/__init__.py
> +        entry = async_config_entry_by_device_id(event.data[CONF_DEVICE_ID])
Seems the `hass` is missing.

2020-12-17 13:25 UTC, postlund commented on custom_components/localtuya/__init__.py
> +        entry = async_config_entry_by_device_id(event.data[CONF_DEVICE_ID])
Ah, right!

2020-12-17 19:14 UTC, ultratoto14 approved these changes

2020-12-17 20:36 UTC, merged

2020-12-17 20:36 UTC, postlund commented
🎉