Cover uppercase and new commands
rospogrigio/localtuya pull request #81
Opened 2020-10-14 08:11 UTC by rospogrigio

Introduced FZ_ZZ as available open_close commands for covers.
Also introduced autodetection of lower-upper case for commands.

2020-10-14 08:16 UTC, postlund reviewed
Should be added to YAML example also, right?

2020-10-14 08:18 UTC, rospogrigio commented
Yeah, I always forget that... commited.

2020-10-14 08:20 UTC, postlund approved these changes
That's what code reviews are for!

2020-10-14 08:27 UTC, rospogrigio commented
Yeah I know! 😄 Now let's wait for juan11perez confirmation that it works...

2020-10-16 08:37 UTC, rospogrigio commented
So @juan11perez, now that we have solved some problems let's continue here with your issues. The aim here is for you to use this PR without patching the code and making sure that everything works on your side. 
So, please apply this PR and let us know whether:
1) you are able to configure your devices, both using config flow and using YAML
2) the devices are working properly: they are available and you can operate them both via the position slider and via the arrows, and the feedback works properly
Please note that on your devices this will conflict with the Tuya app, so leave it closed or disconnect your phone.
You should not need to use template covers, the device should just work fine natively.
Let us know how it goes, thank you.

2020-10-16 14:09 UTC, juan11perez commented
@rospogrigio thank you for your help. 
So i downloaded this branch (Cover uppercase and new commands) just now and it has the same problem i reported in [link](https://community.home-assistant.io/t/tuya-local-with-energy-monitoring-and-without-tuya-convert/173564/364)

Even manually changing the bottom section of cover.py I couldnt get it to appear as "available" nor operate arrows. Slider works,nothing else.

So I downloaded the last release (3.0) via hacs, modified the bottom of cover.py like this:

`    async def async_open_cover(self, **kwargs):
        """Open the cover."""
        _LOGGER.debug("Launching command %s to cover ", "FZ")
        await self._device.set_dp("FZ", self._dp_id)

    async def async_close_cover(self, **kwargs):
        """Close cover."""
        _LOGGER.debug("Launching command %s to cover ", "ZZ")
        await self._device.set_dp("ZZ", self._dp_id)

    async def async_stop_cover(self, **kwargs):
        """Stop the cover."""
        _LOGGER.debug("Launching command %s to cover ", COVER_STOP_CMD)
        await self._device.set_dp(COVER_STOP_CMD.upper(), self._dp_id)`

And again I have a working cover with the same minor problem of the state: see below picture

![Screenshot_2020-10-16_18-00-59](https://user-images.githubusercontent.com/30061229/96268849-9ad6fd00-0fda-11eb-9e6c-6d81353c6351.png)


so in this example the buttons, slider works. But even though its closed the window-icon is open and shows open in hass

2020-10-16 14:26 UTC, rospogrigio commented
I would proceed one step at a time. Let's first make your configuration work without patching the code.
Please stick to this PR trying to refrain from patching the code.
Try to configure the device both via YAML (with the option `open_close_cmds: "fz_zz"`) and via config flow. 
Please post logs in case of failure so we can figure out what's going on.
Once we have the device available and the commands running, we'll go for the second issue.

2020-10-18 09:17 UTC, juan11perez commented
ok, I tried this branch all possible combinations with configflow and yaml. The entity remains unavailable.
the slider mover the cover, but nothing else works
these are the logs

`2020-10-18 13:11:55 DEBUG (MainThread) [custom_components.localtuya.discovery] Listening to broadcasts on UDP port 6666 and 6667
2020-10-18 13:11:57 DEBUG (MainThread) [custom_components.localtuya.discovery] Discovered device: {'ip': '192.168.1.60', 'gwId': 'bf491025d0e05f3881lire', 'active': 2, 'ablilty': 0, 'encrypt': True, 'productKey': 'keyqwddxxv8ukxkj', 'version': '3.3'}
2020-10-18 13:11:58 DEBUG (MainThread) [custom_components.localtuya.discovery] Discovered device: {'ip': '192.168.1.61', 'gwId': 'bf7f1048822137a241xsva', 'active': 2, 'ablilty': 0, 'encrypt': True, 'productKey': 'keyqwddxxv8ukxkj', 'version': '3.3'}
2020-10-18 13:11:59 DEBUG (MainThread) [custom_components.localtuya.discovery] Discovered device: {'ip': '192.168.1.64', 'gwId': '42787240807d3a0103b8', 'active': 2, 'ability': 0, 'mode': 0, 'encrypt': True, 'productKey': '8wq8cNNPt1bbXgYC', 'version': '3.3'}
2020-10-18 13:11:59 DEBUG (MainThread) [custom_components.localtuya.discovery] Discovered device: {'ip': '192.168.1.62', 'gwId': 'bff18195435913278dtpnb', 'active': 2, 'ablilty': 0, 'encrypt': True, 'productKey': 'keyqwddxxv8ukxkj', 'version': '3.3'}
2020-10-18 13:11:59 DEBUG (MainThread) [custom_components.localtuya.discovery] Discovered device: {'ip': '192.168.1.65', 'gwId': '186822745002916f521b', 'active': 2, 'ability': 0, 'mode': 0, 'encrypt': True, 'productKey': '8wq8cNNPt1bbXgYC', 'version': '3.3'}
2020-10-18 13:12:37 DEBUG (MainThread) [custom_components.localtuya.pytuya] [186822745002916f521b] Started heartbeat loop
2020-10-18 13:12:37 DEBUG (MainThread) [custom_components.localtuya.pytuya] [186822745002916f521b] Sending command heartbeat (device type: type_0a)
2020-10-18 13:12:37 DEBUG (MainThread) [custom_components.localtuya.pytuya] [186822745002916f521b] Paylod: b'{}'
2020-10-18 13:12:37 DEBUG (MainThread) [custom_components.localtuya.pytuya] [186822745002916f521b] Waiting for sequence number -100
2020-10-18 13:12:37 DEBUG (MainThread) [custom_components.localtuya.pytuya] [186822745002916f521b] Sending command status (device type: type_0a)
2020-10-18 13:12:37 DEBUG (MainThread) [custom_components.localtuya.pytuya] [186822745002916f521b] Paylod: b'{"gwId":"186822745002916f521b","devId":"186822745002916f521b"}'
2020-10-18 13:12:37 DEBUG (MainThread) [custom_components.localtuya.pytuya] [186822745002916f521b] Waiting for sequence number 1
2020-10-18 13:12:37 DEBUG (MainThread) [custom_components.localtuya.pytuya] [186822745002916f521b] Got heartbeat response
2020-10-18 13:12:37 DEBUG (MainThread) [custom_components.localtuya.pytuya] [186822745002916f521b] Decode payload: b''
2020-10-18 13:12:37 DEBUG (MainThread) [custom_components.localtuya.pytuya] [186822745002916f521b] Decrypted payload: {}
2020-10-18 13:12:37 DEBUG (MainThread) [custom_components.localtuya.pytuya] [186822745002916f521b] Dispatching sequence number 1
2020-10-18 13:12:37 DEBUG (MainThread) [custom_components.localtuya.pytuya] [186822745002916f521b] Decode payload: b'\xda\xc4S!H\xaa\xed\x96\xa2&\xf0c?U\xa3\x9a\x12\x8f\xa5*\t\xd7\xf7\x8f\xef\xb0\x01l\xa4\x88\xcc\xf82\xc4v3\xf7\xb1S>\xb1`aU(^~y\xf8W\x99\xc0\xdb\x98\xbc\xbf|*\xe6\x1f\x85.\xafe\xa1i\xa5\xc6\x9e\x93\x17\xac\x84\x80.;,\x9c\x8e]'
2020-10-18 13:12:37 DEBUG (MainThread) [custom_components.localtuya.pytuya] [186822745002916f521b] Decrypted payload: {"devId":"186822745002916f521b","dps":{"101":0,"102":"STOP","103":true}}
2020-10-18 13:12:37 DEBUG (MainThread) [custom_components.localtuya.pytuya] [186822745002916f521b] Closing connection
2020-10-18 13:12:37 DEBUG (MainThread) [custom_components.localtuya.pytuya] [186822745002916f521b] Connection lost: None
2020-10-18 13:12:37 DEBUG (MainThread) [custom_components.localtuya.pytuya] [186822745002916f521b] Closing connection
2020-10-18 13:13:28 DEBUG (MainThread) [custom_components.localtuya.common] Connecting to 192.168.1.65 (186822745002916f521b)
2020-10-18 13:13:28 DEBUG (MainThread) [custom_components.localtuya.common] Waiting 0 seconds before connecting
2020-10-18 13:13:28 DEBUG (MainThread) [custom_components.localtuya.common] Connecting to 192.168.1.65
2020-10-18 13:13:29 DEBUG (MainThread) [custom_components.localtuya.pytuya] [186822745002916f521b] Started heartbeat loop
2020-10-18 13:13:29 DEBUG (MainThread) [custom_components.localtuya.pytuya] [186822745002916f521b] Sending command heartbeat (device type: type_0a)
2020-10-18 13:13:29 DEBUG (MainThread) [custom_components.localtuya.pytuya] [186822745002916f521b] Paylod: b'{}'
2020-10-18 13:13:29 DEBUG (MainThread) [custom_components.localtuya.pytuya] [186822745002916f521b] Waiting for sequence number -100
2020-10-18 13:13:29 DEBUG (MainThread) [custom_components.localtuya.common] Retrieving initial state
2020-10-18 13:13:29 DEBUG (MainThread) [custom_components.localtuya.pytuya] [186822745002916f521b] Sending command status (device type: type_0a)
2020-10-18 13:13:29 DEBUG (MainThread) [custom_components.localtuya.pytuya] [186822745002916f521b] Paylod: b'{"gwId":"186822745002916f521b","devId":"186822745002916f521b"}'
2020-10-18 13:13:29 DEBUG (MainThread) [custom_components.localtuya.pytuya] [186822745002916f521b] Waiting for sequence number 1
2020-10-18 13:13:29 DEBUG (MainThread) [custom_components.localtuya.pytuya] [186822745002916f521b] Got heartbeat response
2020-10-18 13:13:29 DEBUG (MainThread) [custom_components.localtuya.pytuya] [186822745002916f521b] Decode payload: b''
2020-10-18 13:13:29 DEBUG (MainThread) [custom_components.localtuya.pytuya] [186822745002916f521b] Decrypted payload: {}
2020-10-18 13:13:29 DEBUG (MainThread) [custom_components.localtuya.pytuya] [186822745002916f521b] Dispatching sequence number 1
2020-10-18 13:13:29 DEBUG (MainThread) [custom_components.localtuya.pytuya] [186822745002916f521b] Decode payload: b'\xda\xc4S!H\xaa\xed\x96\xa2&\xf0c?U\xa3\x9a\x12\x8f\xa5*\t\xd7\xf7\x8f\xef\xb0\x01l\xa4\x88\xcc\xf82\xc4v3\xf7\xb1S>\xb1`aU(^~y\xf8W\x99\xc0\xdb\x98\xbc\xbf|*\xe6\x1f\x85.\xafe\xa1i\xa5\xc6\x9e\x93\x17\xac\x84\x80.;,\x9c\x8e]'
2020-10-18 13:13:29 DEBUG (MainThread) [custom_components.localtuya.pytuya] [186822745002916f521b] Decrypted payload: {"devId":"186822745002916f521b","dps":{"101":0,"102":"STOP","103":true}}
2020-10-18 13:13:49 DEBUG (MainThread) [custom_components.localtuya.pytuya] [186822745002916f521b] Sending command heartbeat (device type: type_0a)
2020-10-18 13:13:49 DEBUG (MainThread) [custom_components.localtuya.pytuya] [186822745002916f521b] Paylod: b'{}'
2020-10-18 13:13:49 DEBUG (MainThread) [custom_components.localtuya.pytuya] [186822745002916f521b] Waiting for sequence number -100
2020-10-18 13:13:49 DEBUG (MainThread) [custom_components.localtuya.pytuya] [186822745002916f521b] Got heartbeat response
2020-10-18 13:13:49 DEBUG (MainThread) [custom_components.localtuya.pytuya] [186822745002916f521b] Decode payload: b''
2020-10-18 13:13:49 DEBUG (MainThread) [custom_components.localtuya.pytuya] [186822745002916f521b] Decrypted payload: {}
2020-10-18 13:14:09 DEBUG (MainThread) [custom_components.localtuya.pytuya] [186822745002916f521b] Sending command heartbeat (device type: type_0a)
2020-10-18 13:14:09 DEBUG (MainThread) [custom_components.localtuya.pytuya] [186822745002916f521b] Paylod: b'{}'
2020-10-18 13:14:09 DEBUG (MainThread) [custom_components.localtuya.pytuya] [186822745002916f521b] Waiting for sequence number -100
2020-10-18 13:14:09 DEBUG (MainThread) [custom_components.localtuya.pytuya] [186822745002916f521b] Got heartbeat response
2020-10-18 13:14:09 DEBUG (MainThread) [custom_components.localtuya.pytuya] [186822745002916f521b] Decode payload: b''
2020-10-18 13:14:09 DEBUG (MainThread) [custom_components.localtuya.pytuya] [186822745002916f521b] Decrypted payload: {}
2020-10-18 13:14:29 DEBUG (MainThread) [custom_components.localtuya.pytuya] [186822745002916f521b] Sending command heartbeat (device  [...]

2020-10-19 08:17 UTC, rospogrigio commented
@juan11perez , there is something I don't understand. You say the device is unavailable, yet you can move it with the slider... how is that possible? When I have an unavailable entity, all its buttons and sliders are disabled so I cannot operate them.
How are you moving it?

2020-10-19 12:03 UTC, juan11perez commented
@rospogrigio 
In HA developers tab, the entity state in homeassistant says unavailable. 
in the cover entity/card the slider moves the cover, but after a minute it reverts back to 0 and the cover phisically stays where it is.
the arrows are not visisble 
and the state is unavailable.

2020-10-19 12:09 UTC, rospogrigio commented
And you confirm that with what is currently in master you see the device available?
@postlund do you have an idea of what is going on here? There are only slight modifications that do not explain what's happening...

2020-10-19 12:13 UTC, juan11perez commented
with the master changing below part as per initial suggestion works, except for the issue already reported where the state doesnt change, but arrows work, slider works, etc 
as per above picture

`    async def async_open_cover(self, **kwargs):
        """Open the cover."""
        _LOGGER.debug("Launching command %s to cover ", "FZ")
        await self._device.set_dp("FZ", self._dp_id)

    async def async_close_cover(self, **kwargs):
        """Close cover."""
        _LOGGER.debug("Launching command %s to cover ", "ZZ")
        await self._device.set_dp("ZZ", self._dp_id)

    async def async_stop_cover(self, **kwargs):
        """Stop the cover."""
        _LOGGER.debug("Launching command %s to cover ", COVER_STOP_CMD)
        await self._device.set_dp(COVER_STOP_CMD.upper(), self._dp_id)`

2020-10-19 12:22 UTC, rospogrigio commented
And with unpatched master?

2020-10-19 12:24 UTC, juan11perez commented
with unpatched master is the initial problem where the slider would work and reflect actual cover postion, but the buttons didnt do anything. The buttons only worked when adding the FF ZZ commands

2020-10-19 12:31 UTC, rospogrigio commented
Ok try what I have just pushed and tell me how it goes...

2020-10-19 12:39 UTC, juan11perez commented
to confirm, do you mean 3.0.1 release?

2020-10-19 12:41 UTC, rospogrigio commented
> to confirm, do you mean 3.0.1 release?

No, what I have just pushed in this PR.

2020-10-19 13:06 UTC, juan11perez commented
ok, thank you. 
I have done it. downloaded this branch and same result. this is what it looks like 
![Screenshot_2020-10-19_16-51-08](https://user-images.githubusercontent.com/30061229/96453563-b258f480-122b-11eb-977c-306d5088c550.png)

2020-10-19 13:09 UTC, rospogrigio commented
Logs?

2020-10-19 13:27 UTC, postlund commented
> And you confirm that with what is currently in master you see the device available?
> @postlund do you have an idea of what is going on here? There are only slight modifications that do not explain what's happening...

Not sure I understand why I'm afraid. The fact that the slider is available despite the entity being unavailable sounds like a front end bug to me.

2020-10-19 13:28 UTC, rospogrigio commented
@juan11perez as a curiosity: which HA version are you running?

2020-10-19 13:37 UTC, juan11perez commented
@rospogrigio 
currentlly on lastest HA running 116.4

2020-10-19 13:39 UTC, rospogrigio commented
And what about the logs?

2020-10-19 13:48 UTC, juan11perez commented
@rospogrigio 
please see below
`2020-10-19 17:42:48 DEBUG (MainThread) [custom_components.localtuya.common] Connecting to 192.168.1.64 (42787240807d3a0103b8)
2020-10-19 17:42:48 DEBUG (MainThread) [custom_components.localtuya.common] Connecting to 192.168.1.65 (186822745002916f521b)
2020-10-19 17:42:48 DEBUG (MainThread) [custom_components.localtuya.common] Waiting 0 seconds before connecting
2020-10-19 17:42:48 DEBUG (MainThread) [custom_components.localtuya.common] Waiting 0 seconds before connecting
2020-10-19 17:42:48 DEBUG (MainThread) [custom_components.localtuya.common] Connecting to 192.168.1.64
2020-10-19 17:42:48 DEBUG (MainThread) [custom_components.localtuya.common] Connecting to 192.168.1.65
2020-10-19 17:42:48 DEBUG (MainThread) [custom_components.localtuya.pytuya] [42787240807d3a0103b8] Started heartbeat loop
2020-10-19 17:42:48 DEBUG (MainThread) [custom_components.localtuya.pytuya] [42787240807d3a0103b8] Sending command heartbeat (device type: type_0a)
2020-10-19 17:42:48 DEBUG (MainThread) [custom_components.localtuya.pytuya] [42787240807d3a0103b8] Send payload: b'{}'
2020-10-19 17:42:48 DEBUG (MainThread) [custom_components.localtuya.pytuya] [42787240807d3a0103b8] Waiting for sequence number -100
2020-10-19 17:42:48 DEBUG (MainThread) [custom_components.localtuya.pytuya] [186822745002916f521b] Started heartbeat loop
2020-10-19 17:42:48 DEBUG (MainThread) [custom_components.localtuya.pytuya] [186822745002916f521b] Sending command heartbeat (device type: type_0a)
2020-10-19 17:42:48 DEBUG (MainThread) [custom_components.localtuya.pytuya] [186822745002916f521b] Send payload: b'{}'
2020-10-19 17:42:48 DEBUG (MainThread) [custom_components.localtuya.pytuya] [186822745002916f521b] Waiting for sequence number -100
2020-10-19 17:42:48 DEBUG (MainThread) [custom_components.localtuya.common] Retrieving initial state
2020-10-19 17:42:48 DEBUG (MainThread) [custom_components.localtuya.pytuya] [42787240807d3a0103b8] Sending command status (device type: type_0a)
2020-10-19 17:42:48 DEBUG (MainThread) [custom_components.localtuya.pytuya] [42787240807d3a0103b8] Send payload: b'{"gwId":"42787240807d3a0103b8","devId":"42787240807d3a0103b8"}'
2020-10-19 17:42:48 DEBUG (MainThread) [custom_components.localtuya.pytuya] [42787240807d3a0103b8] Waiting for sequence number 1
2020-10-19 17:42:48 DEBUG (MainThread) [custom_components.localtuya.common] Retrieving initial state
2020-10-19 17:42:48 DEBUG (MainThread) [custom_components.localtuya.pytuya] [186822745002916f521b] Sending command status (device type: type_0a)
2020-10-19 17:42:48 DEBUG (MainThread) [custom_components.localtuya.pytuya] [186822745002916f521b] Send payload: b'{"gwId":"186822745002916f521b","devId":"186822745002916f521b"}'
2020-10-19 17:42:48 DEBUG (MainThread) [custom_components.localtuya.pytuya] [186822745002916f521b] Waiting for sequence number 1
2020-10-19 17:42:48 DEBUG (MainThread) [custom_components.localtuya.pytuya] Dispatching message TuyaMessage(seqno=0, cmd=9, retcode=0, payload=b'', crc=2958142211)
2020-10-19 17:42:48 DEBUG (MainThread) [custom_components.localtuya.pytuya] [42787240807d3a0103b8] Got heartbeat response
2020-10-19 17:42:48 DEBUG (MainThread) [custom_components.localtuya.pytuya] [42787240807d3a0103b8] Decrypted payload: {}
2020-10-19 17:42:48 DEBUG (MainThread) [custom_components.localtuya.pytuya] Dispatching message TuyaMessage(seqno=0, cmd=9, retcode=0, payload=b'', crc=2958142211)
2020-10-19 17:42:48 DEBUG (MainThread) [custom_components.localtuya.pytuya] [186822745002916f521b] Got heartbeat response
2020-10-19 17:42:48 DEBUG (MainThread) [custom_components.localtuya.pytuya] Dispatching message TuyaMessage(seqno=1, cmd=10, retcode=0, payload=b'U\xf8\x8e\xaf\x00\xfd\x04\xab\xa0\nN\x8b\xb9 U\xf8\xfbu\xabP>\x88\x83\xe5\xb7\x10wi\xcd?0%\x0fIX\xc0\xc2\x9dM\xdb\xbc\xd4\xed\xad\x99\xe5\xfc6z\x0bw\x90\xc6A\x80\xa6&"\xec^}\xa1\t\xafP\xf6\xb2\x8b\x83>\x9c\xe5\xf3c\x8b\x97\x0cla\xa4', crc=996718216)
2020-10-19 17:42:48 DEBUG (MainThread) [custom_components.localtuya.pytuya] [42787240807d3a0103b8] Dispatching sequence number 1
2020-10-19 17:42:48 DEBUG (MainThread) [custom_components.localtuya.pytuya] [186822745002916f521b] Decrypted payload: {}
2020-10-19 17:42:48 DEBUG (MainThread) [custom_components.localtuya.pytuya] Dispatching message TuyaMessage(seqno=1, cmd=10, retcode=0, payload=b'\xda\xc4S!H\xaa\xed\x96\xa2&\xf0c?U\xa3\x9a\x12\x8f\xa5*\t\xd7\xf7\x8f\xef\xb0\x01l\xa4\x88\xcc\xf82\xc4v3\xf7\xb1S>\xb1`aU(^~y\xf8W\x99\xc0\xdb\x98\xbc\xbf|*\xe6\x1f\x85.\xafe\xa1i\xa5\xc6\x9e\x93\x17\xac\x84\x80.;,\x9c\x8e]', crc=832755706)
2020-10-19 17:42:48 DEBUG (MainThread) [custom_components.localtuya.pytuya] [186822745002916f521b] Dispatching sequence number 1
2020-10-19 17:42:48 DEBUG (MainThread) [custom_components.localtuya.pytuya] [42787240807d3a0103b8] Decrypted payload: {"devId":"42787240807d3a0103b8","dps":{"101":90,"102":"STOP","103":true}}
2020-10-19 17:42:48 DEBUG (SyncWorker_2) [custom_components.localtuya.cover] Status updated: STOP
2020-10-19 17:42:48 DEBUG (MainThread) [custom_components.localtuya.pytuya] [186822745002916f521b] Decrypted payload: {"devId":"186822745002916f521b","dps":{"101":0,"102":"STOP","103":true}}
2020-10-19 17:42:48 DEBUG (SyncWorker_11) [custom_components.localtuya.cover] Status updated: STOP
2020-10-19 17:42:58 DEBUG (MainThread) [custom_components.localtuya.common] Connecting to 192.168.1.60 (bf491025d0e05f3881lire)
2020-10-19 17:42:58 DEBUG (MainThread) [custom_components.localtuya.common] Connecting to 192.168.1.61 (bf7f1048822137a241xsva)
2020-10-19 17:42:58 DEBUG (MainThread) [custom_components.localtuya.common] Connecting to 192.168.1.62 (bff18195435913278dtpnb)
2020-10-19 17:42:58 DEBUG (MainThread) [custom_components.localtuya.common] Connecting to 192.168.1.63 (bf9237dadb720259detsti)
2020-10-19 17:42:59 DEBUG (MainThread) [custom_components.localtuya.common] Waiting 0 seconds before connecting
2020-10-19 17:42:59 DEBUG (MainThread) [custom_components.localtuya.common] Waiting 0 seconds before connecting
2020-10-19 17:42:59 DEBUG (MainThread) [custom_components.localtuya.common] Waiting 0 seconds before connecting
2020-10-19 17:42:59 DEBUG (MainThread) [custom_components.localtuya.common] Waiting 0 seconds before connecting
2020-10-19 17:42:59 DEBUG (MainThread) [custom_components.localtuya.common] Connecting to 192.168.1.60
2020-10-19 17:42:59 DEBUG (MainThread) [custom_components.localtuya.common] Connecting to 192.168.1.61
2020-10-19 17:42:59 DEBUG (MainThread) [custom_components.localtuya.common] Connecting to 192.168.1.62
2020-10-19 17:42:59 DEBUG (MainThread) [custom_components.localtuya.common] Connecting to 192.168.1.63
2020-10-19 17:42:59 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf7f1048822137a241xsva] Started heartbeat loop
2020-10-19 17:42:59 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf7f1048822137a241xsva] Sending command heartbeat (device type: type_0a)
2020-10-19 17:42:59 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf7f1048822137a241xsva] Send payload: b'{}'
2020-10-19 17:42:59 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf7f1048822137a241xsva] Waiting for sequence number -100
2020-10-19 17:42:59 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bff18195435913278dtpnb] Started heartbeat loop
2020-10-19 17:42:59 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bff18195435913278dtpnb] Sending command heartbeat (device type: type_0a)
2020-10-19 17:42:59 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bff18195435913278dtpnb] Send payload: b'{}'
2020-10-19 17:42:59 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bff18195435913278dtpnb] Waiting for sequence number -100
2020-10-19 17:42:59 DEBUG (MainThread) [custom_components.localtuya.common] Retrieving initial state
2020-10-19 17:42:59 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf7f1048822137a241xsva] Sending command status (device type: type_0a)
2020-10-19 17:42:59 D [...]

2020-10-19 14:25 UTC, juan11perez commented
@rospogrigio 
so I dont know python.  This is me on trial and error.

I just moved this section like so:
basically moved the equiality before the open and close commands and i now have same result as when manually changing the commands. 
arrows work, slider works, but I think the state works it's just inverted. i.e close is open, open is closed.

`       self._open_cmd = self._open_cmd.upper()
        self._close_cmd = self._close_cmd.upper()
        self._stop_cmd = self._stop_cmd.upper()

    async def async_open_cover(self, **kwargs):
        """Open the cover."""
        _LOGGER.debug("Launching command %s to cover ", self._open_cmd)
        await self._device.set_dp(self._open_cmd, self._dp_id)

    async def async_close_cover(self, **kwargs):
        """Close cover."""
        _LOGGER.debug("Launching command %s to cover ", self._close_cmd)
        await self._device.set_dp(self._close_cmd, self._dp_id)

    async def async_stop_cover(self, **kwargs):
        """Stop the cover."""
        _LOGGER.debug("Launching command %s to cover ", COVER_STOP_CMD)
        await self._device.set_dp(COVER_STOP_CMD, self._dp_id)

    def status_updated(self):
        """Device status was updated."""
        self._state = self.dps(self._dp_id)
        _LOGGER.debug("Status updated: %s", self._state)
#        if self._state.isupper():


        if self.has_config(CONF_CURRENT_POSITION_DP):
            self._current_cover_position = self.dps(
                self._config[CONF_CURRENT_POSITION_DP]
            )
        else:
            self._current_cover_position = 50`

2020-10-19 15:15 UTC, rospogrigio commented
OK now I noticed that I was not handling the Stop command correctly. Try it now.
Then, I also thought that there was an inversion with the open/close status but it's quite weird. Let's figure it out after we have made the entity available and working with the arrows.

2020-10-19 15:22 UTC, juan11perez commented
@rospogrigio 
ok so this works. arrows, slider. only the state remains incorrect. 
it's just inverted. see below picture

![Uploading Screenshot_2020-10-19_19-22-18.png…]()

2020-10-19 15:37 UTC, rospogrigio commented
Please try with this, I added some debugging.
Actually the screenshot you posted is coherent, but it depends on the real status of your device...are you saying that it was totally open in this situation? 
And can you post a screenshot of the Tuya app in this situation? (You'll probably need to kill HA because they can't coexist)

2020-10-19 15:57 UTC, juan11perez commented
@rospogrigio 
updated and no change. see picture

![Screenshot_2020-10-19_19-52-30](https://user-images.githubusercontent.com/30061229/96475206-cb21d400-1244-11eb-9206-eed262ed838a.png)

cover is now fully closed. and i confirm is physically fully closed

and tuya app picture below

![Uploading Screenshot_20201019-195500_TuyaSmart.jpg…]()

2020-10-19 16:03 UTC, juan11perez commented
and some logs

`2020-10-19 20:00:26 DEBUG (MainThread) [custom_components.localtuya.common] Connecting to 192.168.1.64 (42787240807d3a0103b8)
2020-10-19 20:00:26 DEBUG (MainThread) [custom_components.localtuya.common] Connecting to 192.168.1.65 (186822745002916f521b)
2020-10-19 20:00:26 DEBUG (MainThread) [custom_components.localtuya.common] Waiting 0 seconds before connecting
2020-10-19 20:00:26 DEBUG (MainThread) [custom_components.localtuya.common] Waiting 0 seconds before connecting
2020-10-19 20:00:26 DEBUG (MainThread) [custom_components.localtuya.common] Connecting to 192.168.1.64
2020-10-19 20:00:26 DEBUG (MainThread) [custom_components.localtuya.common] Connecting to 192.168.1.65
2020-10-19 20:00:26 DEBUG (MainThread) [custom_components.localtuya.pytuya] [42787240807d3a0103b8] Started heartbeat loop
2020-10-19 20:00:26 DEBUG (MainThread) [custom_components.localtuya.pytuya] [42787240807d3a0103b8] Sending command heartbeat (device type: type_0a)
2020-10-19 20:00:26 DEBUG (MainThread) [custom_components.localtuya.pytuya] [42787240807d3a0103b8] Send payload: b'{}'
2020-10-19 20:00:26 DEBUG (MainThread) [custom_components.localtuya.pytuya] [42787240807d3a0103b8] Waiting for sequence number -100
2020-10-19 20:00:26 DEBUG (MainThread) [custom_components.localtuya.common] Retrieving initial state
2020-10-19 20:00:26 DEBUG (MainThread) [custom_components.localtuya.pytuya] [42787240807d3a0103b8] Sending command status (device type: type_0a)
2020-10-19 20:00:26 DEBUG (MainThread) [custom_components.localtuya.pytuya] [42787240807d3a0103b8] Send payload: b'{"gwId":"42787240807d3a0103b8","devId":"42787240807d3a0103b8"}'
2020-10-19 20:00:26 DEBUG (MainThread) [custom_components.localtuya.pytuya] [42787240807d3a0103b8] Waiting for sequence number 1
2020-10-19 20:00:26 DEBUG (MainThread) [custom_components.localtuya.pytuya] Dispatching message TuyaMessage(seqno=0, cmd=9, retcode=0, payload=b'', crc=2958142211)
2020-10-19 20:00:26 DEBUG (MainThread) [custom_components.localtuya.pytuya] [42787240807d3a0103b8] Got heartbeat response
2020-10-19 20:00:26 DEBUG (MainThread) [custom_components.localtuya.pytuya] [42787240807d3a0103b8] Decrypted payload: {}
2020-10-19 20:00:26 DEBUG (MainThread) [custom_components.localtuya.pytuya] Dispatching message TuyaMessage(seqno=1, cmd=10, retcode=0, payload=b'U\xf8\x8e\xaf\x00\xfd\x04\xab\xa0\nN\x8b\xb9 U\xf8\xfbu\xabP>\x88\x83\xe5\xb7\x10wi\xcd?0%\xc4\xfd\xd1!\xa7M\xa2\xc4\x06hLu\xd7ix\x95R\x05*\x05 \xaf\x7f\x1a\x05q\xa2\x83\xc9&\x87*!i\x81U\xe8\xd2\x12\xff\x05\xfa\xa0\xd6,d\xd4\xd7', crc=2843684653)
2020-10-19 20:00:26 DEBUG (MainThread) [custom_components.localtuya.pytuya] [42787240807d3a0103b8] Dispatching sequence number 1
2020-10-19 20:00:26 DEBUG (MainThread) [custom_components.localtuya.pytuya] [42787240807d3a0103b8] Decrypted payload: {"devId":"42787240807d3a0103b8","dps":{"101":100,"102":"STOP","103":true}}
2020-10-19 20:00:26 DEBUG (SyncWorker_53) [custom_components.localtuya.cover] Status updated: STOP
2020-10-19 20:00:26 DEBUG (MainThread) [custom_components.localtuya.cover] IS_CLOSE: 100
2020-10-19 20:00:27 DEBUG (MainThread) [custom_components.localtuya.pytuya] [186822745002916f521b] Started heartbeat loop
2020-10-19 20:00:27 DEBUG (MainThread) [custom_components.localtuya.pytuya] [186822745002916f521b] Sending command heartbeat (device type: type_0a)
2020-10-19 20:00:27 DEBUG (MainThread) [custom_components.localtuya.pytuya] [186822745002916f521b] Send payload: b'{}'
2020-10-19 20:00:27 DEBUG (MainThread) [custom_components.localtuya.pytuya] [186822745002916f521b] Waiting for sequence number -100
2020-10-19 20:00:27 DEBUG (MainThread) [custom_components.localtuya.common] Retrieving initial state
2020-10-19 20:00:27 DEBUG (MainThread) [custom_components.localtuya.pytuya] [186822745002916f521b] Sending command status (device type: type_0a)
2020-10-19 20:00:27 DEBUG (MainThread) [custom_components.localtuya.pytuya] [186822745002916f521b] Send payload: b'{"gwId":"186822745002916f521b","devId":"186822745002916f521b"}'
2020-10-19 20:00:27 DEBUG (MainThread) [custom_components.localtuya.pytuya] [186822745002916f521b] Waiting for sequence number 1
2020-10-19 20:00:27 DEBUG (MainThread) [custom_components.localtuya.pytuya] Dispatching message TuyaMessage(seqno=0, cmd=9, retcode=0, payload=b'', crc=2958142211)
2020-10-19 20:00:27 DEBUG (MainThread) [custom_components.localtuya.pytuya] [186822745002916f521b] Got heartbeat response
2020-10-19 20:00:27 DEBUG (MainThread) [custom_components.localtuya.pytuya] [186822745002916f521b] Decrypted payload: {}
2020-10-19 20:00:27 DEBUG (MainThread) [custom_components.localtuya.pytuya] Dispatching message TuyaMessage(seqno=1, cmd=10, retcode=0, payload=b'\xda\xc4S!H\xaa\xed\x96\xa2&\xf0c?U\xa3\x9a\x12\x8f\xa5*\t\xd7\xf7\x8f\xef\xb0\x01l\xa4\x88\xcc\xf8{\x7fYj\\\x11\xf6\xb7\xe3\x92i6[\xda\xb0=\x0cs\xd2w*\x04\xdeK@\xe4\xe2\xc9H^\x1f5\xce\x12\x06\xcf\xed0\xc0\xb1\xb3\xb2\x80\xb9\x1fi@\xed', crc=3140969740)
2020-10-19 20:00:27 DEBUG (MainThread) [custom_components.localtuya.pytuya] [186822745002916f521b] Dispatching sequence number 1
2020-10-19 20:00:27 DEBUG (MainThread) [custom_components.localtuya.pytuya] [186822745002916f521b] Decrypted payload: {"devId":"186822745002916f521b","dps":{"101":100,"102":"STOP","103":true}}
2020-10-19 20:00:27 DEBUG (SyncWorker_34) [custom_components.localtuya.cover] Status updated: STOP
2020-10-19 20:00:27 DEBUG (MainThread) [custom_components.localtuya.cover] IS_CLOSE: 100
2020-10-19 20:00:31 DEBUG (MainThread) [custom_components.localtuya.common] Connecting to 192.168.1.60 (bf491025d0e05f3881lire)
2020-10-19 20:00:31 DEBUG (MainThread) [custom_components.localtuya.common] Connecting to 192.168.1.61 (bf7f1048822137a241xsva)
2020-10-19 20:00:31 DEBUG (MainThread) [custom_components.localtuya.common] Connecting to 192.168.1.62 (bff18195435913278dtpnb)
2020-10-19 20:00:31 DEBUG (MainThread) [custom_components.localtuya.common] Connecting to 192.168.1.63 (bf9237dadb720259detsti)
2020-10-19 20:00:31 DEBUG (MainThread) [custom_components.localtuya.common] Waiting 0 seconds before connecting
2020-10-19 20:00:31 DEBUG (MainThread) [custom_components.localtuya.common] Waiting 0 seconds before connecting
2020-10-19 20:00:31 DEBUG (MainThread) [custom_components.localtuya.common] Waiting 0 seconds before connecting
2020-10-19 20:00:31 DEBUG (MainThread) [custom_components.localtuya.common] Waiting 0 seconds before connecting
2020-10-19 20:00:31 DEBUG (MainThread) [custom_components.localtuya.common] Connecting to 192.168.1.60
2020-10-19 20:00:31 DEBUG (MainThread) [custom_components.localtuya.common] Connecting to 192.168.1.61
2020-10-19 20:00:31 DEBUG (MainThread) [custom_components.localtuya.common] Connecting to 192.168.1.62
2020-10-19 20:00:31 DEBUG (MainThread) [custom_components.localtuya.common] Connecting to 192.168.1.63
2020-10-19 20:00:32 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bff18195435913278dtpnb] Started heartbeat loop
2020-10-19 20:00:32 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bff18195435913278dtpnb] Sending command heartbeat (device type: type_0a)
2020-10-19 20:00:32 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bff18195435913278dtpnb] Send payload: b'{}'
2020-10-19 20:00:32 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bff18195435913278dtpnb] Waiting for sequence number -100
2020-10-19 20:00:32 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf7f1048822137a241xsva] Started heartbeat loop
2020-10-19 20:00:32 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf7f1048822137a241xsva] Sending command heartbeat (device type: type_0a)
2020-10-19 20:00:32 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf7f1048822137a241xsva] Send payload: b'{}'
2020-10-19 20:00:32 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf7f1048822137a241xsva] Waiting for sequence number -100
2020-10-19 20:00:32 DEBUG (MainThread) [custom_components.localtuya.common] Retrieving initial  [...]

2020-10-19 20:28 UTC, rospogrigio commented
> @rospogrigio
> updated and no change. see picture
> 
> cover is now fully closed. and i confirm is physically fully closed
> 
> and tuya app picture below

But then @juan11perez , this means that localtuya is behaving exactly like regular Tuya app, so I believe you have just mounted the device in the wrong way, maybe you have inverted the wires... when you press the "up" arrow, does it open or close? Does it behave the same as Tuya app?

2020-10-20 04:08 UTC, juan11perez commented
@rospogrigio 
no, the localtuya slider reflects the tuya app position. but the localtuya status is opposite of the tuya app. see these 2 pictures
In the tuya app, the cover is open and it shows 100%

![Screenshot_20201020-080054_TuyaSmart](https://user-images.githubusercontent.com/30061229/96538871-aa8c6500-12aa-11eb-8164-ccf6f6e2c7ac.jpg)

in localtuya, the slider is fully open, the curtain is fully open. but the status is close.

![Screenshot_2020-10-20_08-04-01](https://user-images.githubusercontent.com/30061229/96538953-e0314e00-12aa-11eb-9134-b6a5e41b537d.png)

Moreover there's no wiring confusion. The motor simply plugs into mains, nothing further is required.
this is the link to the  [product](https://www.zemismart.com/zemismart-smart-curtain-alexa-google-home-electric-stage-curtain-motorized-tuya-wifi-curtain-motor-with-track-p0160-p0160.html)

As mentioned earlier, your cover.py defines open as 100% in line 109. Looking at the tuya app, the case here is the opposite. i.e. open is 0% and close is 100%

2020-10-20 07:33 UTC, rospogrigio commented
This is a bit confusing. So, just to clarify things, please fill in this little form, just leaving the correct answer in the brackets:
1) Does open button actually open the cover? With Tuya app: [Yes/No]   with localtuya: [Yes/No]
2) If you move the slider towards 100%, does it open or close the cover? With Tuya app: [Open/Close]   with localtuya: [Open/Close]
3) When the slider is at 100%, is it reported to be Open or Closed? With Tuya app: [Open/Closed]   with localtuya: [Open/Closed]

Depending on your answers, I believe we might have to add an option to reverse the slider position, but I need to understand clearly how to implement it so I need these final answers.
Thank you

2020-10-20 09:13 UTC, juan11perez commented
@rospogrigio 
once again thank you very much for your time. See below.

Does open button actually open the cover? With Tuya app: [Yes] with localtuya: [Yes]
Note. in tuya the button is labelled as Turn On (see above picture) and it opens the cover.

If you move the slider towards 100%, does it open or close the cover? With Tuya app: [Close] with localtuya: [Close]

When the slider is at 100%, is it reported to be Open or Closed? With Tuya app: [Open/Closed] neither. It only reports "CurrentPosition: 100%" in line with the above app picture. 

with localtuya: [Open]

2020-10-20 09:57 UTC, rospogrigio commented
OK, very clear now. I added a new Option called "invert_position" that you should set to True.
Please test this PR with both YAML and config flow and let me know if it works as expected.

2020-10-20 10:28 UTC, rospogrigio commented
@postlund , I asked you to review this PR again... also, since a new set of commands has appeared (1-2-3 probably), shall I open a new PR or shall I add them to this? Let me know

2020-10-20 10:31 UTC, postlund commented
@rospogrigio I'm on it! I suggest that you open a new PR for that.

2020-10-20 10:36 UTC, postlund requested changes
Minor things otherwise looks good 👍

2020-10-20 10:36 UTC, postlund commented on custom_components/localtuya/cover.py
> +        if self._config[CONF_POSITION_INVERTED]:
```python
return 0 if self.config[CONF_POSITION_INVERTED] else 100
```

2020-10-20 10:36 UTC, postlund commented on custom_components/localtuya/cover.py
> +        if self._config[CONF_POSITION_INVERTED]:
Same

2020-10-20 11:39 UTC, juan11perez commented
@rospogrigio 
this is what i get with configfow

![Screenshot_2020-10-20_15-16-12](https://user-images.githubusercontent.com/30061229/96580741-cc590c80-12e9-11eb-887d-52dadbab11b0.png)

And with this yaml

`- host: 192.168.1.64
  device_id: 42787240807d3a0103b8
  local_key: 0ec2b8e7852101f4
  friendly_name: curtains_bruno # BRUNO CURTAINS
  protocol_version: "3.3"
  entities:
  - platform: cover
    friendly_name: curtains_bruno
    id: 102
    open_close_cmds: fz_zz #open_close
    positioning_mode: position
    current_position_dp: 101
    set_position_dp: 101
    span_time: 25 
    invert_position: true`

config check in HA just keeps spinning and doesn't provie any feedback. 
The first time I tried it gave an error along the lines of cant get CONF_POSITION_INVERTED from const.py

Also none of the other tuya switches worked (unavailable) and after a while i couldn't remove entities from the integrations, localtuya page in HA

2020-10-20 11:56 UTC, rospogrigio commented
@postlund I am having issues validating a boolean option, I always get the "Unknown error occurred".. I have been trying both vol.Boolean() and cv.boolean, check_config passes but the config flow gives error, which is the proper way to do this?

2020-10-20 12:14 UTC, rospogrigio commented
@juan11perez my bad, I had not tested it. Now it should work fine, please try it out

2020-10-20 12:31 UTC, juan11perez commented
@rospogrigio 
configflow now loads but the state still doesn't work.  I checked the box with the option inverted position
see picture

![Screenshot_2020-10-20_16-25-27](https://user-images.githubusercontent.com/30061229/96586042-72f4db80-12f1-11eb-9538-671ec902d930.png)

with yaml im getting this error when adding " invert_position: True "

`                          Invalid config for [localtuya]: extra keys not allowed @ data['localtuya'][0]['entities'][0]['current_position_dp']. Got 101
extra keys not allowed @ data['localtuya'][0]['entities'][0]['invert_position']. Got True
extra keys not allowed @ data['localtuya'][0]['entities'][0]['open_close_cmds']. Got 'fz_zz'
extra keys not allowed @ data['localtuya'][0]['entities'][0]['positioning_mode']. Got 'position'
extra keys not allowed @ data['localtuya'][0]['entities'][0]['set_position_dp']. Got 101
extra keys not allowed @ data['localtuya'][0]['entities'][0]['span_time']. Got 25
value is not allowed for dictionary value @ data['localtuya'][0]['entities'][0]['platform']. Got 'cover'. (See /config/configuration.yaml, line 98). `


maybe it's not  invert_position: True ?

2020-10-20 13:05 UTC, rospogrigio commented
Sorry @juan11perez , I had written nonsense code... looks like I'm very tired these days 😆 
Now it should definitely work, please confirm...

2020-10-20 16:18 UTC, juan11perez commented
@rospogrigio 
ok so nearly there. all buttons work, the state is correct. However, when the cover is fully open (slider is full left, postion = 0%) the open arrow stays on. 

At this point, you'd need the open arrow to "deactivate" and the down arrow to be hightlighted so you can close the cover next.
see below picture

![Screenshot_2020-10-20_20-15-07](https://user-images.githubusercontent.com/30061229/96614655-6e401f80-1311-11eb-8105-6f3af6f75adb.png)

2020-10-20 19:22 UTC, rospogrigio commented
Can you close it fully and post a screenshot?

2020-10-20 20:43 UTC, rospogrigio commented
OK @juan11perez now I have it clear. actually HA wants 100 to be fully open, and 0 to be fully closed:
https://developers.home-assistant.io/docs/core/entity/cover/
So I had to really invert the slider, so now you'll see it inverted with respect to Tuya app (I mean, right is open and left is closed), and the position will be inverted (like 30 instead of 70) but everything should work this time.
Please note that I had to merge from another PR that changed the syntax so you'll have to either change the YAML, replacing:
`open_close_cmds: "fz_zz"`
with:
`commands_set: "fz_zz_stop"`
 or repeat the config flow accordingly.
Please tell me that it works, this time 😉

2020-10-21 04:52 UTC, juan11perez commented
@rospogrigio 
Success!!!!
Open 
![open](https://user-images.githubusercontent.com/30061229/96674182-3bca0d00-1379-11eb-95cf-b99639ecc0b9.png)

closed
![closed](https://user-images.githubusercontent.com/30061229/96674193-45537500-1379-11eb-89a4-56dc80ac6bdb.png)

buttons, slider and positionning work.

works with this yaml

`- host: 192.168.1.64
  device_id: 42787240807d3a0103b8
  local_key: key
  friendly_name: curtains_bruno 
  protocol_version: "3.3"
  entities:
  - platform: cover
    friendly_name: curtains_bruno
    id: 102
    commands_set: fz_zz_stop
    positioning_mode: position
    current_position_dp: 101
    set_position_dp: 101
    span_time: 25 
    position_inverted: true`

works with this configflow

![configflow](https://user-images.githubusercontent.com/30061229/96674300-8d729780-1379-11eb-81b7-bbeb05fb7ffe.png)

and instantaneous response.

Thank you very much for getting it to Perfect!

2020-10-21 07:01 UTC, rospogrigio commented
Hurray!! Sorry for taking so long for the fix but I'm a little rusty these days, plus I couldn't believe that we really needed to invert the slider. Glad we made it work also for this device!
@postlund this PR is ready for your review 😊

2020-10-21 07:09 UTC, postlund requested changes
Just one minor thing then we are ready to roll 👍

2020-10-21 07:09 UTC, postlund commented on custom_components/localtuya/cover.py
> +            curr_pos = self.dps(self._config[CONF_CURRENT_POSITION_DP])
`dps_conf`

2020-10-21 07:25 UTC, juan11perez commented
@rospogrigio  well thank you for your persistence.  It provided the desired result.  it works!
And thank you once again to you and @postlund  for providing this component to the community.

2020-10-21 08:17 UTC, rospogrigio commented on custom_components/localtuya/cover.py
> +            curr_pos = self.dps(self._config[CONF_CURRENT_POSITION_DP])
right, done!

2020-10-21 08:20 UTC, postlund approved these changes

2020-10-21 08:23 UTC, merged